version: "3.8"
services:

    db:
        image: mysql
        container_name: nrh_gp_mysql
        restart: always
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
            - "3306"
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: nrh_gp_phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8081:80
        environment:
            PMA_HOST: db
        networks:
            - dev
    web:
        image: nginx:latest
        container_name: nrh_gp_nginx
        volumes:
            - ./code:/code
            - ./laravel:/laravel
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/laravel.conf:/etc/nginx/conf.d/laravel.conf
        ports:
            - "8080:80"
        networks:
            - dev

    php:
        build: 
            context: ./docker/php
        # image: php:8.1-fpm
        container_name: nrh_gp_php_fpm
        volumes:
            - ./code:/code
            - ./symfony:/symfony
            - ./laravel:/laravel
        networks:
            - dev

networks:
    dev: